train:
  _target_: src.datasets.DlaDataset
  dataset_path: "dla_dataset"
  dataset_length: null
  audio_ref: True
  video_ref: False
  refs_cnt: 2  # Only 1 or 2 [2 for bss, 1 for tss] 
  name: "train"
  override: True
  instance_transforms: ${transforms.instance_transforms.train}
val:
  _target_: src.datasets.DlaDataset
  dataset_path: "dla_dataset"
  dataset_length: null
  audio_ref: True
  video_ref: False
  refs_cnt: 2
  name: "val"
  override: True
  instance_transforms: ${transforms.instance_transforms.train}
# test:
#   _target_: src.datasets.DlaDataset
#   dataset_path: "dla_dataset"
#   dataset_length: null
#   audio_ref: True
#   video_ref: False 
#   name: "test"
#   override: False
#   instance_transforms: ${transforms.instance_transforms.train}
