_target_: src.model.DPRNNModel
feature_dim: 8 # 64
num_of_speakers: 2
num_dprnn_layers: 1
norm_type: LayerNorm  # [LayerNorm, RMSNorm]

feature_extractor_config:
  kernel_size: 5
  padding: 2
  stride: 1

split_config:
  chunks_length: 2000
  hop_size: 500

dprnn_block_config:
  feature_dim: ${model.feature_dim}
  hidden_channels: 8
  rnn_type: GRU  # [LSTM, GRU]
  norm_type: ${model.norm_type}
  dropout: 0
  bidirectional: True




