_target_: src.model.DPRNNModel
audio_only: True
feature_dim: 64 # 64
num_of_speakers: 2
num_dprnn_layers: 6
norm_type: LayerNorm  # [LayerNorm, RMSNorm]

feature_extractor_config:
  kernel_size: 3
  padding: 1
  stride: 2

split_config:
  chunks_length: 100
  hop_size: 50

dprnn_block_config:
  feature_dim: ${model.feature_dim}
  hidden_channels: 128
  rnn_type: LSTM  # [LSTM, GRU]
  norm_type: ${model.norm_type}
  dropout: 0
  bidirectional: True




